### ISSUE TITLE
No source code 

### ISSUE THREAD

**Issue by yamsergey** [ashdavies/preferences-store#1]
Please add source code into the release

**Comment by yamsergey** [comment]
Seems to be my local problem. The release include sources https://jitpack.io/com/github/ashdavies/preferences-store/0.1.6/preferences-store-0.1.6-sources.jar as it defined in https://raw.githubusercontent.com/sky-uk/gradle-maven-plugin/master/gradle-mavenizer.gradle . I will close the issue.

**Comment by ashdavies** [comment]
Thanks for verifying
